In [1]:
import numpy as np

In [2]:
def gaussian_elim(X):
    X_2 = X.copy().astype(np.float64)
    leading = 0
    m, n = X.shape # m rows, n columns
    for r in range(0,m):
        if n <= leading:
            return X_2
        i = r
        while X_2[i,leading]==0:
            i+=1
            if m==i:
                i=r
                leading+=1
                if n==leading:
                    return X_2
        if i != r:
            temp = np.copy(X_2[r,:])
            X_2[r,:] = np.copy(X_2[i,:])
            X_2[i,:] = temp
        X_2[r,:] = X_2[r,:]/X_2[r,leading]
        for i in range(0,m):
                if i != r:
                    X_2[i,:]-=X_2[r,:]*X_2[i,leading]
        leading+=1
    return X_2

In [3]:
A = np.array([[1, 0, 1, 1],
             [1, 0, 1, 1],
             [0, 1, 1, 1],
             [1, 1, 1, 0],
             [1, 1, 1, 0]], dtype=np.float64)
print(gaussian_elim(A))
#The result should look like
# [[ 1.,  0.,  0., -1.],
#  [ 0.,  1.,  0., -1.],
#  [-0., -0.,  1.,  2.],
#  [ 0.,  0.,  0.,  0.],
#  [ 0.,  0.,  0.,  0.]]

[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [-0. -0.  1.  2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [4]:
B = np.array([[2, 0, 3, 1, 0, 2],
             [1, 3, 2, 0, 3, 1],
             [3, 2, 3, 1, 1, 2]])
print(gaussian_elim(B))
#The result should look like
# [[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
#  [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
#  [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]

[[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
 [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
 [-0.         -0.          1.          0.09090909  0.54545455  0.54545455]]
