In [1]:
import numpy as np

In [2]:
# Find orthonormal basis using Gram-Schmidt 
def gram_schmidt(A):
    A_1 = A.astype(np.float64)
    orthonormal_basis = np.zeros_like(A_1)
    count = 0
    for a in A_1.T:
         u = np.copy(a)
         for i in range(0, count):
            u -= np.dot(np.dot(orthonormal_basis[:, i].T, a), orthonormal_basis[:, i]) # subtract u's projection on i from u
         e = u / np.linalg.norm(u)  # normalization
         orthonormal_basis[:, count] = e
         count += 1
    return orthonormal_basis

F = np.array([[1,2,1],[0,3,1],[1,-1,2]]) # all columns in F are linear independent, F can be put into Gram-Schmidt algorithm
G = np.array([[1,3,3],[-2,2,10],[5,-1,17]]) # all columns in G are linear independent, G can be put into Gram-Schmidt algorithm
print(gram_schmidt(F))
print(gram_schmidt(G))

[[ 0.70710678  0.40824829 -0.57735027]
 [ 0.          0.81649658  0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]]
[[ 0.18257419  0.89442719 -0.40824829]
 [-0.36514837  0.4472136   0.81649658]
 [ 0.91287093  0.          0.40824829]]


In [3]:
def orthogonality_checker(A): # check the result of Gram-Schmidt
    A_1 = A.astype(np.float64)
    n = np.size(A_1,1)
    for i in range(0,n):
        if abs(1-np.linalg.norm(A_1[:,i])) > 1e-6:
            return False
        else:
            for j in range(i+1,n):
                if np.dot(A[:,i].T,A[:,j]) < 1e-6:
                    pass
                else:
                    return False
    return True

true_test = np.eye(3,3)
false_test = np.ones((3,3))
print('\nCHECKING TRUE TEST (SHOULD RETURN TRUE):')
print(orthogonality_checker(true_test))
print('\nCHECKING FALSE TEST (SHOULD RETURN FALSE):')
print(orthogonality_checker(false_test))


CHECKING TRUE TEST (SHOULD RETURN TRUE):
True

CHECKING FALSE TEST (SHOULD RETURN FALSE):
False
